[tox]
envlist=
    py314-core
    py314-lint
    py314-script
    py314-deps
    py314-cve

[testenv]
passenv=
    PYTEST_ADDOPTS
basepython=
    py314: python3.14

[common-install]
deps=
    -r{toxinidir}/requirements.txt
    -r{toxinidir}/requirements_test.txt

[common-core]
deps={[common-install]deps}
commands=
    pytest {posargs:tests}

[common-lint]
deps={[common-install]deps}
commands=
    ruff check {toxinidir}/ethstaker_deposit {toxinidir}/tests
    mypy --config-file {toxinidir}/mypy.ini -p ethstaker_deposit

[common-script]
deps=
    -r{toxinidir}/requirements_test.txt  # for async-pytest
commands=
    python {toxinidir}/test_deposit_script.py
    python {toxinidir}/test_btec_script.py

[testenv:py314-core]
deps={[common-core]deps}
commands={[common-core]commands}

[testenv:py314-lint]
deps={[common-lint]deps}
commands={[common-lint]commands}

[testenv:py314-script]
deps={[common-script]deps}
commands={[common-script]commands}

[testenv:py314-deps]
deps=
    -r{toxinidir}/requirements.txt
    -r{toxinidir}/requirements_test.txt
commands=
    python {toxinidir}/scripts/check_dependencies_sync.py

[testenv:py314-cve]
deps={[common-install]deps}
commands=
    pip-audit -r {toxinidir}/requirements.txt -r {toxinidir}/requirements_test.txt --no-deps --strict --desc
